//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class New
    {
        public int IdNew { get; set; }
        public string Title { get; set; }
        public string Decription { get; set; }
        public string Link { get; set; }
        public string Meta { get; set; }
        public Nullable<bool> Hide { get; set; }
        public Nullable<System.DateTime> Datebegin { get; set; }
        public string Images { get; set; }
        public Nullable<int> Order { get; set; }
        public string TitleSp { get; set; }
    }
}
